# Generated by Django 3.1.5 on 2021-01-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myworks',
            options={'verbose_name': 'Моя работа', 'verbose_name_plural': 'Мои работы'},
        ),
        migrations.AlterField(
            model_name='myworks',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Картина'),
        ),
    ]
