# Generated by Django 3.1.5 on 2021-01-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210117_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myworks',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main/static/main/img', verbose_name='Картина'),
        ),
    ]
