# Generated by Django 3.1.5 on 2021-01-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210117_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myworks',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='Картина'),
        ),
    ]
